---
- name: Set access key id
  when: aws_profile.access_key_id is defined
  community.general.ini_file:
    path: "/home/{{ aws_user }}/.aws/credentials"
    section: "{{ aws_profile.name }}"
    option: aws_access_key_id
    value: "{{ aws_profile.access_key_id }}"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: "0600"
    create: true

- name: Set secret access key
  when: aws_profile.secret_access_key is defined
  no_log: true
  community.general.ini_file:
    path: "/home/{{ aws_user }}/.aws/credentials"
    section: "{{ aws_profile.name }}"
    option: aws_secret_access_key
    value: "{{ aws_profile.secret_access_key }}"
    owner: "{{ aws_user }}"
    group: "{{ aws_user }}"
    mode: "0600"
    create: true
