---

aws_tools_install_cli: true

aws_user: "{{ ansible_facts.user_id | default('') }}"

awscli_v2_version: "2.15.57"
awscli_v2_arch: "x86_64"
awscli_v2_install_dir: /usr/local/aws-cli
awscli_v2_bin_dir: /usr/local/bin

aws_profiles: []

aws_write_credentials: true
